#! /bin/sh
# kcminputrc Mouse cursorTheme 'breeze_cursors'
kcminputrc_mouse_cursortheme=breeze_cursors
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=0
# ksplashrc KSplash Theme Breeze
ksplashrc_ksplash_theme=org.kde.breeze.desktop
# ksplashrc KSplash Engine KSplashQML
ksplashrc_ksplash_engine=KSplashQML
# kdeglobals KScreen ScaleFactor ''
kdeglobals_kscreen_scalefactor=2
# kdeglobals KScreen ScreenScaleFactors ''
kdeglobals_kscreen_screenscalefactors='eDP1=2;DP1=2;DP2=2;HDMI1=2;HDMI2=2;VIRTUAL1=2;'
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=192
