#! /bin/sh

#                    ___           ___         ___           ___
#     _____         /  /\         /  /\       /__/\         /__/\
#    /  /::\       /  /:/_       /  /::\     _\_ \:\       |  |::\
#   /  /:/\:\     /  /:/ /\     /  /:/\:\   /__/\ \:\      |  |:|:\  
#  /  /:/~/::\   /  /:/ /::\   /  /:/~/:/  _\_ \:\ \:\   __|__|:|\:\
# /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/  /__/\ \:\ \:\ /__/::::| \:\ 
# \  \:\/:/~/:/ \  \:\/:/~/:/ \  \:\/:/   \  \:\ \:\/:/ \  \:\~~\__\/ 
#  \  \::/ /:/   \  \::/ /:/   \  \::/     \  \:\ \::/   \  \:\
#   \  \:\/:/     \__\/ /:/     \  \:\      \  \:\/:/     \  \:\
#    \  \::/        /__/:/       \  \:\      \  \::/       \  \:\
#     \__\/         \__\/         \__\/       \__\/         \__\/

###################
## configuration ##
###################

## workspace name
## font needed wuncon-siji
bspc monitor -d '' '' '' '' '' '' '' ''

## common bspwm configuration
bspc config border_width        3
bspc config window_gap         	16
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config top_padding 24
bspc config bottom_padding 48


## color settings
bspc config focused_border_color "#98971a" 
bspc config normal_border_color "#928374"


##################
## window rules ##
##################

## workspace 1 (labs)
bspc rule -a URxvt follow=on focus=on
bspc rule -a Xfce4-terminal follow=on focus=on
bspc rule -a Termite follow=on focus=on

## workspace 2 (web browsers)
bspc rule -a Firefox-esr follow=on focus=on
bspc rule -a Chromium follow=on focus=on
bspc rule -a Opera follow=on focus=on
bspc rule -a Transmission-gtk follow=on focus=on

## workspace 3 (file-manager)
bspc rule -a Thunar follow=on focus=on
bspc rule -a File-roller follow=on focus=on

## workspace 4 (text-editors)
bspc rule -a Geany follow=on focus=on
bspc rule -a libreoffice-startcenter follow=on focus=on
bspc rule -a libreoffice follow=on focus=on
bspc rule -a Soffice follow=on focus=on
bspc rule -a libreoffice-base follow=on focus=on
bspc rule -a libreoffice-calc follow=on focus=on
bspc rule -a libreoffice-draw follow=on focus=on
bspc rule -a libreoffice-impress follow=on focus=on
bspc rule -a libreoffice-math follow=on focus=on
bspc rule -a libreoffice-writer follow=on focus=on
bspc rule -a Wps follow=on focus=on
bspc rule -a Et follow=on focus=on
bspc rule -a Wpp follow=on focus=on

## workspace 5 (graphic-utilities)
bspc rule -a Nitrogen follow=on focus=on
bspc rule -a Font-manager state=tiled follow=on focus=on
bspc rule -a Evince follow=on focus=on
bspc rule -a Gucharmap follow=on focus=on

## workspace 6 (multimedia)
bspc rule -a Audacity follow=on focus=on
bspc rule -a Vlc follow=on focus=on
bspc rule -a mpv follow=on focus=on
bspc rule -a Ghb follow=on focus=on
bspc rule -a Xfburn follow=on focus=on

## workspace 7 (graphics-editors)
bspc rule -a Gimp follow=on focus=on
bspc rule -a Gimp-2.8 follow=on focus=on
bspc rule -a Inkscape follow=on focus=on
bspc rule -a Oomox follow=on focus=on

## workspace 8 (system-settings)
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Xfce4-settings-manager state=floating follow=on
bspc rule -a Lightdm-gtk-greeter-settings state=floating follow=on
bspc rule -a System-config-printer.py state=floating follow=on
bspc rule -a Lxtask state=floating follow=on
bspc rule -a GParted follow=on focus=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Exo-helper-1 state=floating follow=on
bspc rule -a Lxrandr state=floating follow=on
bspc rule -a Arandr state=floating follow=on

## need to be floating
bspc rule -a Audacious state=floating follow=on
bspc rule -a Viewnior state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Gpicview state=floating follow=on

## don't manage my conky & systemtray :/
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

###############
## autostart ##
###############

# xmodmap
xmodmap ~/.Xmodmap

# Load bitmap fonts
xset fp+ ~/.fonts/misc &

## reload compton
pkill compton
compton -b &

# system tray
#pkill stalonetray
#stalonetray &

# network applet
nm-applet &

# clipboard manager
pkill clipit
clipit &

# volume icon
#pkill volumeicon
#volumeicon &

# keybind daemon
pkill sxhkd
sxhkd &

## music is my only friend :(
mpd &

## reload the xsettingsd, a minimal x settings daemon
pkill xsettingsd
xsettingsd &

## set the wallpaper
feh --bg-fill ~/.config/bspwm/wallpaper.jpg

## load dunst
pkill dunst
dunst &

## reload the cursor theme
xsetroot -cursor_name left_ptr

## load xfce4-panel
pkill xfce4-panel
xfce4-panel &

## load panel script
#pkill panel-bspwm
#panel-bspwm &

## or polybar?
pkill polybar
polybar -c ~/.config/bspwm/polybar top &
